### ISSUE TITLE
Updating Octave version? 

### ISSUE THREAD

**Issue by agahkarakuzu** [joergbrech/moxunit-action#12]
@joergbrech I will soon upgrade the Octave version to 5.2.0 (Ubuntu 20.04 based) in the Docker images I built for our software.  Currently we are pulling from `qmrlab/octaveci:v4.2.2`, I can update this to the new one if you agree. 

Best!

**Comment by joergbrech** [comment]
Sure, go for it! 😃

**Comment by joergbrech** [comment]
Closed with #29
